// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS_tIWAS34SbM0HL5dou5TYHkxCOEadJA',
    appId: '1:280401408455:web:b62eeb9339915182fca9e2',
    messagingSenderId: '280401408455',
    projectId: 'lettershelf-49537',
    authDomain: 'lettershelf-49537.firebaseapp.com',
    storageBucket: 'lettershelf-49537.appspot.com',
    measurementId: 'G-6M494REFPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYrb52HJvX_DVarZGkiZr2bI198Wps08A',
    appId: '1:280401408455:android:467d1a7c79d62577fca9e2',
    messagingSenderId: '280401408455',
    projectId: 'lettershelf-49537',
    storageBucket: 'lettershelf-49537.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG8ItFnOR9_0iqmWC26uqczc27dvXUALc',
    appId: '1:280401408455:ios:dda14fea0eb217f6fca9e2',
    messagingSenderId: '280401408455',
    projectId: 'lettershelf-49537',
    storageBucket: 'lettershelf-49537.appspot.com',
    iosClientId: '280401408455-qmt93jji4kek0126flnfc5321h15fvrs.apps.googleusercontent.com',
    iosBundleId: 'com.lettershelf.letterShelf',
  );
}
